#!/usr/bin/env python3
"""Plot a Pearson-correlation curve from an existing TSV of per-example metrics."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Iterable, List

import numpy as np


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--metrics-tsv",
        type=Path,
        required=True,
        help="TSV generated by compare_teacher_student.py (must contain the correlation column).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Destination for the Pearson curve plot (e.g., PNG).",
    )
    parser.add_argument(
        "--column",
        type=str,
        default="student_vs_experiment_profile_pearson",
        help="Column name in the TSV to plot (defaults to student vs experiment profile Pearson).",
    )
    parser.add_argument(
        "--rolling-window",
        type=int,
        default=0,
        help="Optional rolling window size for smoothing (0 disables smoothing).",
    )
    parser.add_argument(
        "--sort",
        action="store_true",
        help="Sort the correlations before plotting (useful for ECDF-like visualization).",
    )
    return parser.parse_args(argv)


def load_column(tsv_path: Path, column: str) -> np.ndarray:
    values: List[float] = []
    with tsv_path.open("r", newline="") as handle:
        reader = csv.DictReader(handle, delimiter="\t")
        if column not in reader.fieldnames:
            raise ValueError(
                f"Column '{column}' not found in TSV. Available columns: {reader.fieldnames}"
            )
        for row in reader:
            value = row[column]
            if value in ("", "nan", "NaN", "NA"):
                values.append(np.nan)
            else:
                values.append(float(value))

    arr = np.array(values, dtype=np.float64)
    return arr


def rolling_mean(arr: np.ndarray, window: int) -> np.ndarray:
    if window <= 1:
        return arr
    kernel = np.ones(window, dtype=np.float64) / window
    return np.convolve(arr, kernel, mode="valid")


def main(argv: Iterable[str] | None = None) -> None:
    args = parse_args(argv)

    correlations = load_column(args.metrics_tsv, args.column)

    mask = ~np.isnan(correlations)
    num_nans = np.count_nonzero(~mask)
    if num_nans:
        print(f"Ignoring {num_nans} NaN entries when plotting.")

    correlations = correlations[mask]

    if args.sort:
        correlations = np.sort(correlations)

    smoothed = correlations
    if args.rolling_window > 1:
        smoothed = rolling_mean(correlations, args.rolling_window)

    try:
        import matplotlib.pyplot as plt
    except ImportError as exc:
        raise RuntimeError(
            "matplotlib is required to plot the Pearson curve. Install it via `pip install matplotlib`."
        ) from exc

    output_path = args.output.expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
 
    plt.figure(figsize=(10, 4))
    x = np.arange(len(smoothed))
    plt.scatter(x, smoothed, s=10, label=args.column)
    plt.axhline(0.0, color="gray", linestyle="--", linewidth=0.8)
    plt.xlabel("Example index (after filtering/sorting)")
    plt.ylabel("Pearson correlation")
    title = "Pearson correlation curve"
    if args.sort:
        title += " (sorted)"
    if args.rolling_window > 1:
        title += f" (rolling mean, window={args.rolling_window})"
    plt.title(title)
    plt.tight_layout()
    plt.legend(loc="best")
    plt.savefig(output_path)
    plt.close()
    print(f"Saved Pearson curve plot to {output_path}")


if __name__ == "__main__":
    main()
